# .github/workflows/update-ical.yml
name: Update iCal to JSON

on:
  workflow_dispatch:
  schedule:
    # --- 18:10 Paris (veille) ---
    - cron: '10 16 * * 1-5'  # été (UTC+2)
    - cron: '10 17 * * 1-5'  # hiver (UTC+1)

    # --- 06:10 Paris (matin) ---
    - cron: '10 4 * * 1-5'   # été
    - cron: '10 5 * * 1-5'   # hiver

    # --- 12:10 Paris (midi) ---
    - cron: '10 10 * * 1-5'  # été
    - cron: '10 11 * * 1-5'  # hiver

permissions:
  contents: write

concurrency:
  group: update-ical
  cancel-in-progress: true

env:
  ICS_URL: ${{ vars.ICS_URL || secrets.ICS_URL }}
  OUTPUT_FILE: data/latest.json
  TZ: Europe/Paris
  HORIZON_DAYS: 60
  PAST_DAYS: 7

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages   # nécessaire si ICS_URL est défini dans cet environnement

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (ade/)
        run: npm ci --prefix ade || npm i --prefix ade

      - name: Generate latest.json (root/data)
        run: node ade/scripts/ics_to_json.mjs

      - name: Commit if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/latest.json
          if git diff --quiet --staged; then
            echo "No changes to commit."
            exit 0
          else
            git commit -m "Update latest.json ($(date -u +%FT%TZ))"
            git push
          fi
